services:
  # 后端服务 (包含前端静态文件)
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "80:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./apks:/app/apks
      - ../deploy/auto_build.sh:/app/auto_build.sh
      - ../:/app/android-project
    environment:
      - NODE_ENV=production
      - PORT=3001