services:
  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./apks:/app/apks
      - ../deploy/auto_build.sh:/app/auto_build.sh
      - ../:/app/android-project
    environment:
      - NODE_ENV=production

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    command: |
      sh -c '
      cat > /etc/nginx/conf.d/default.conf << EOF
      server {
          listen 80;
          client_max_body_size 10M;
          
          location / {
              proxy_pass http://frontend:80;
              proxy_set_header Host \$$host;
              proxy_set_header X-Real-IP \$$remote_addr;
              proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$$scheme;
          }

          location /api/ {
              proxy_pass http://backend:3001;
              proxy_set_header Host \$$host;
              proxy_set_header X-Real-IP \$$remote_addr;
              proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$$scheme;
          }
      }
      EOF
      nginx -g "daemon off;"
      '
    depends_on:
      - frontend
      - backend