services:
  # 后端服务 (包含前端静态文件)
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./apks:/app/apks
      - ../deploy/auto_build.sh:/app/auto_build.sh
      - ../deploy/domain_manager.py:/app/domain_manager.py
      - ../deploy/simple_domain_manager.py:/app/simple_domain_manager.py
      - ../deploy/keystores:/app/keystores  
      - ../deploy/domain_configs.json:/app/domain_configs.json
      - ../:/app/workspace
    environment:
      - NODE_ENV=production
      - PORT=3001

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    command: |
      sh -c '
      cat > /etc/nginx/conf.d/default.conf << EOF
      # HTTP redirect to HTTPS for aw.viteoai.com
      server {
          listen 80;
          server_name aw.viteoai.com;
          return 301 https://\$$host\$$request_uri;
      }
      
      # HTTPS server for aw.viteoai.com
      server {
          listen 443 ssl http2;
          server_name aw.viteoai.com;
          client_max_body_size 10M;
          
          # SSL configuration
          ssl_certificate /etc/nginx/ssl/*.viteoai.com.crt;
          ssl_certificate_key /etc/nginx/ssl/*.viteoai.com.key;
          
          # Modern SSL configuration
          ssl_protocols TLSv1.2 TLSv1.3;
          ssl_ciphers HIGH:!aNULL:!MD5;
          ssl_prefer_server_ciphers off;
          
          # Security headers
          add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
          add_header X-Frame-Options "SAMEORIGIN" always;
          add_header X-Content-Type-Options "nosniff" always;
          
          location / {
              proxy_pass http://backend:3001;
              proxy_set_header Host \$$host;
              proxy_set_header X-Real-IP \$$remote_addr;
              proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$$scheme;
              proxy_set_header X-Forwarded-Host \$$host;
              proxy_set_header X-Forwarded-Port \$$server_port;
          }
      }
      
      # Default server for other domains (HTTP only)
      server {
          listen 80 default_server;
          client_max_body_size 10M;
          
          location / {
              proxy_pass http://backend:3001;
              proxy_set_header Host \$$host;
              proxy_set_header X-Real-IP \$$remote_addr;
              proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$$scheme;
          }
      }
      EOF
      nginx -g "daemon off;"
      '
    depends_on:
      - backend